name: Shell Commands

on:
  #push:
    #branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  run-shell-command:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup node and check node version
        run: |
          node -v
          npm -v
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9   
      - name: python commands
        run: |
          import platform
          print(platform)
          print(platform.processor)
          python3 -v
        shell: python

    

