name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: node checks
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform)
          print(platform.processor)
        shell: python
  windows-shell-commands:
    runs-on: windows-latest
    steps:
      - name: for location
        run: Get-Location
      - name: location by bash
        run: pwd
        shell: bash

    

